spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/retailops
spring.datasource.username=postgres
spring.datasource.password=Tanguy2025#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true